### ISSUE TITLE
Log in to IBM Bluemix: https://new-console.ng.bluemix.net/login

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#10]
Issue is for: https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/1a
and for https://github.com/ibm-apiconnect/getting-started/blob/master/bluemix/1b/README.md
Could you please add a link to the pre-req if they have not already singed up for APIC on Bluemix

**Comment by deeyas** [comment]
added prereq link to 1a and 1b
