### ISSUE TITLE
Getting Started Discovering APIs dependency issues

### ISSUE THREAD

**Issue by dkshute** [ibm-apiconnect/getting-started#100]
Given that the portal is on Bluemix - as no other scenario for a Getting Started tutorial will work - this unit will not function at all unless the student first makes sure their Bluemix Dev Portal is created.  I do not see where that step is ever taken, even in the PreReq steps for the entire series.

This unit is also dependent on at least tutorial 1a being complete, so that the API is published to the Portal and is available for subscription.  This pre-req needs to be noted.

**Comment by lana-li** [comment]
prereq added
