### ISSUE TITLE
Configure - Customize Dev Portal Show or don't show existing API

### ISSUE THREAD

**Issue by dkshute** [ibm-apiconnect/getting-started#103]
Explore Step 7 - if this setup is done when it should be done - at the very beginning - there won't be any APIs to view, as shown in step 7 and 8.

If you do want the API shown to appear, then at least tutorial 1a is required.

**Comment by lana-li** [comment]
@dkshute I believe this prerequisite was already linked in the beginning of the tutorial, but I will write it out so that it is more clear
