### ISSUE TITLE
Replace an API Product

### ISSUE THREAD

**Issue by jmjabour8** [ibm-apiconnect/getting-started#110]
getting-started/bluemix/manage-versioning/replace.md 

8) Click All APIs. -- A box will pop up asking you if you want to leave, otherwise unsaved changes will be lost.  Have to click save or changes won't be made.

11) Click Stage. -- "Click Stage to Sandbox."  If you don't stage to sandbox, and stage to something else, you get different options when clicking the 3 dots.

Other than those two things, very clear tutorial, great job!

**Comment by dkshute** [comment]
Step 8 - step 7 instructs user to save thus box does not appear.
Step 9 - clarification added
