### ISSUE TITLE
Supercede an API Product

### ISSUE THREAD

**Issue by jmjabour8** [ibm-apiconnect/getting-started#111]
getting-started/bluemix/manage-versioning/supercede.md 

6) Change the Version to 3.0.0. 
-- How do I do this?  When I click the 3 dots in step 5, changing the version isn't an option.  

21)  Click Supercede >> Subscriptions. 
-- Little confused by this step.  What do I supercede, where is the button to supercede -- is it with the 3 dots?  The picture here isn't too helpful.  And what does supercede have to do with subscriptions?  Am I missing a button or something?

22) Click the three vertical dots on the Weather Provider API Product 2.0.0 line. Select Manage. 
-- Where is the option to click Manage?  I don't see that as an option, is it because I couldn't complete step 21 or another previous step?

**Comment by dkshute** [comment]
Step 6 - steps added
Step 7 - should say Community >> Subscriptions.  Corrected
Step 8 - doing 7 fixes this.
