### ISSUE TITLE
Replacement Tutorial Feedback

### ISSUE THREAD

**Issue by winstojl** [ibm-apiconnect/getting-started#113]
Step 8 (Click All APIs) – Does not say APIs, but says Products… A/B Testing?

![image](https://user-images.githubusercontent.com/8562088/30137211-2892fcb4-9317-11e7-89ee-5ce701f5f219.png)

Step 11 (Change Version) – Already done (?) 

Step 12 (Click Stage) – Drops down with option (on my screen, it says Sandbox)… but which one should you click?

**Comment by dkshute** [comment]
Step 8 and Step 11 - I think you did not execute step 4 to switch from products to APIs.  You then changed the version on the product not the API, which is why you thought it was done in step 11.  You didn't see All APIs because you were in Products.
Step 12 - added some clarification
