### ISSUE TITLE
Deprecate bullet

### ISSUE THREAD

**Issue by lana-li** [ibm-apiconnect/getting-started#116]
Question raised by Jennifer Raisig (ID):

**Managing APIs and product versions**
In the second set of bullets, Deprecate, Retire, Archive, and Delete are listed. However, the tutorial does not mention Deprecate. Can I remove that bullet from the list on this page?

**Comment by dkshute** [comment]
Deprecating a product happens in the Supercede tutorial - the superceded product is automatically deprecated.
I think the bullet should remain.
