### ISSUE TITLE
Archiving and deleting products

### ISSUE THREAD

**Issue by lana-li** [ibm-apiconnect/getting-started#117]
Question raised by Jennifer Raisig (ID):

**Archiving and Deleting API products**
Under the Archiving an API product section, can you verify that step 8 has the correct screen capture? I ask because step 7 says to click the list view icon. Step 8 says to select "Archived". The image under step 8 seems to be from a vertical ellipsis menu. Is there perhaps a step missing, like "click the vertical ellipsis on the weather-provider-api-product-3.0.0. Published line"? Something just doesn't flow right between those two steps.

**Comment by dkshute** [comment]
Yup, wrong image in step 8.  Updated.
