### ISSUE TITLE
Gif for testing

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#20]
Issue is for https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/1a

Click ► to test your API proxy's target invocation

Can you include a gif for the testing section. That's what Zach has. It will be almost same i guess

**Comment by deeyas** [comment]
I could create a similar gif to what i did in toolkit/1a. but will put this on backburner for now.

**Comment by deeyas** [comment]
To be consistent, Replaced GIF with better quality PNG in https://github.com/ibm-apiconnect/getting-started/blob/master/toolkit/1a-import/README.md
