### ISSUE TITLE
Test with Explore

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#26]
Issues is for: https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/1a

In this section, could you please add a background around what is the explore tool is about and what does it do more than what they already tested in the assembly tab. 

As it stands today, it does not add any value, rather adds more steps

**Comment by deeyas** [comment]
Added info about Explore Tool  in https://github.com/ibm-apiconnect/getting-started/blob/master/bluemix/1a/README.md
