### ISSUE TITLE
Test with Explore Section

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#28]
#26 is related to this. If you keep this section, the steps outlined are not complete. You would need to add step to click on 'try it' etc, before actually providing the zip code to test

**Comment by deeyas** [comment]
the 'try it' made it to bluemix recently; was not in the apic Bluemix version when this tutorial was written.

besides 'try it' there may be other UI components that changed in the latest Bluemix version. Will need to investigate.
