### ISSUE TITLE
SOAP API URL ?

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#32]
Issues is for : https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/manage-soap-api

In the objective section, it says this tutorial is for SOAP service defined here- https://api.us.apiconnect.ibmcloud.com/dshute-apic-apic-maker/sb/wdata/current

Not sure what the URL is meant to be for. When clicked it it say method not allowed... should we just point to the wsdl or a service landing page which has the wsdl.

Also could we ensure, it opens up on a new tab instead of the same page.

**Comment by dkshute** [comment]
I will change the url to point to the wsdl for the service when the service itself gets implemented in its production location.  It is not there yet.  Thanks.

**Comment by pramodvallanur** [comment]
Cool. This also applies for https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/manage-soap-api

**Comment by dkshute** [comment]
I removed reference to the back end service.
