### ISSUE TITLE
Import steps

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#34]
Issue is for: https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/manage-soap-api

Could we make the first few steps to import consistent across the tutorials for Bluemix- @deeyas has this here: https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/1a

**Comment by pramodvallanur** [comment]
This also applies for https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/exposing-a-soap-service-as-rest.

If we are going towards default product creation later, we don't need step 8.

**Comment by dkshute** [comment]
This doesn't make sense to me - the tutorial referenced by deeyas has a REST interface and has nothing to do with the SOAP API being created here.

**Comment by pramodvallanur** [comment]
hmhm.. what i meant is steps till click on import section.. the steps in both the tutorials are not the same.. after click on the '+' the option the users would go would be different... 

each one of the tutorial need the same set of steps and has different writing, different screen shots etc.

**Comment by dkshute** [comment]
I still don't get this sorry.  Other than the steps to get to API Connect -> Draft APIs, every step is different between tutorials.
I might add that the Bluemix UI has changed and the screens to get to API Connect don't look like 1b any more.

**Comment by pramodvallanur** [comment]
Understand the BM change.

Regarding the consistency, if you read 1b, you will see the steps / text are different. I know it is by different author, i am thinking if we can make it same.

For example steps till before this: 'In the APIs panel, click on Add > Import API from a file or URL' should be the same. In the SOAP Tutorial, this step should read as 'In the APIs panel, click on Add > New OpenAPI from SOAP service'

**Comment by dkshute** [comment]
done
