### ISSUE TITLE
Step 7: Where is the wsdl

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#36]
Issues is for: https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/manage-soap-api

Step 7 says: import the wsdl file from filesystem. 

Where is the wsdl file or the steps to download the wsdl file?

**Comment by dkshute** [comment]
The wsdl comes from the files in the tutorial.  Not sure how that will be delivered; it seems reasonable that the student will first download the course files but maybe not.  If not, the url for the file is what?

**Comment by pramodvallanur** [comment]
if so, should we ask them to clone the repo or atleast point them where to get the file from .. as to get this done, i may not even need to clone.

**Comment by lana-li** [comment]
@dkshute can you upload the file for them to download?

**Comment by dkshute** [comment]
https://github.com/ibm-apiconnect/getting-started/blob/master/bluemix/manage-soap-api/files/weatherprovider.wsdl
