### ISSUE TITLE
Step 8 Consistency

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#37]
Issues is for: https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/manage-soap-api

Could we make Step 8 which is -'Add product' consistent with other tutorials in this package.

As @deeyas  tutorials don't say that step and ask user to create a default product later.

If updated, step 9 is not required.

**Comment by dkshute** [comment]
My environment never presents the Default product option and there are no screen shots in 1b of this.  Advise.

**Comment by pramodvallanur** [comment]
In your tutorials, users create the product during in the initial definition, whereas other tutorials use default product creation, post API definition. 

I am ok with either approach, i want it to be same across, hence marked @deeyas for agreement

**Comment by deeyas** [comment]
During initial definition of API, I ask the user to leave the "generate product" option **unchecked**. 
The reason: We need to introduce one topic/component at a time, and when it's APIC specific, then provide some info about it. 

Introducing "products" while importing APIs seemed premature. Hence, the "default product generation" step right before testing in Assemble.

**Comment by dkshute** [comment]
fixed
