### ISSUE TITLE
Client ID Secret removal

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#38]
In your tutorials, both importing and creating, you don't talk about removing the client_id from the swagger. Do you want to keep that step or remove.

As @Zach-Guilfoyle tutorial here: https://github.com/ibm-apiconnect/getting-started/tree/master/toolkit/1b talks about removing the client id. Even David Shute's says remove Client Id.

We need to be consistent whichever way we go forward.

**Comment by deeyas** [comment]
Not sure in which tutorial I need to remove the client id from swagger.

**Comment by pramodvallanur** [comment]
This is the tutorial which doesnt ask to remove.https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/1a

In your 1b tutorial you have asked the user to remove the client id - step 7 https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/1b

**Comment by deeyas** [comment]
Client ID/secret removal doesn't apply to 1a; already removed in yaml which user imports
