### ISSUE TITLE
Test your API

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#40]
Issue is for :https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/manage-soap-api

If you do the default product generation step than before creation, possibly you can skip steps 2, 3 under testing

**Comment by dkshute** [comment]
Possibly but not guaranteed.  If the user was doing anything else beforehand, the steps in my tutorial are needed.  This way covers all bases.

**Comment by pramodvallanur** [comment]
ok, lets use the default product generation from the overflow menu to be consistent, but lets write these steps as a tooltip if they dont find the right product

**Comment by dkshute** [comment]
A tooltip?

**Comment by pramodvallanur** [comment]
sorry a tooltip was the wrong word. I meant as an extended info. For example, we can say something like this
'See this warning Message: API not added to the product ?' This could be under a section / crib for user to expand

**Comment by dkshute** [comment]
I don't see how you do that kind of click-to-expand with Markdown.

**Comment by lana-li** [comment]
@dkshute let's add the steps in the tutorial for now. whether than will be expanded or not, we can decide later.

**Comment by dkshute** [comment]
fixed
