### ISSUE TITLE
Test section Gif

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#43]
Issue is for: https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/manage-soap-api

For the testing section, could we create gif and also it would consistent with other tutorials of @deeyas

**Comment by dkshute** [comment]
Gif as in mini-movie?

**Comment by pramodvallanur** [comment]
Yes.
@deeyas is that what you have in other tutorials ?

**Comment by dkshute** [comment]
I don't see movie gifs anywhere else - to be consistent.

**Comment by deeyas** [comment]
I've replaced my GIFs with screenshots.
