### ISSUE TITLE
New API Definition Steps

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#45]
Issue is for:
https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/exposing-a-soap-service-as-rest

Could we ensure we are consistent across tutorials: https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/1b @deeyas 

We could just ask the user to input the name, and say leave the remaining as default...  i don't think we need step 7

**Comment by lana-li** [comment]
@dkshute Can you update the SOAP service to return the same data that's shown in bluemix/1b? This will ensure consistency across tutorials.

**Comment by dkshute** [comment]
Lana, the SOAP API already returns the current weather.  While adding "today" is entirely possible, it requires some branching in the assemble step.  I see that 1b already has the branching in it; both my tutorial and Ky's tutorial would need to add branching to handle /today.  It would be easier and faster for the student if 1b took that branch out and only handled current.  Adding branching  logic could then be another tutorial after 1b and left as exercises for students in the tutorials I and Ky did.  Up to you.

**Comment by pramodvallanur** [comment]
my comment above was not about adding / today.. its around the steps required to define a new api.. as noted in another issue, the steps required are the same in all tutorials.
a. find drafts
b. click on drafts
c. click on the '+' icon
the steps and screen shots for these should be same across these.

**Comment by dkshute** [comment]
The Bluemix UI has changed; the screens and steps are now different than what's in 1b.   This is alsdo actually Ky's tutorial.

**Comment by kylien65** [comment]
As mentioned by David, with the recent change in bluemix, the step mentioned in https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/1b @deeyas could be confusing.   Between steps 3 & 4, an extra step to "Add --> New API" is required.

**Comment by deeyas** [comment]
added extra step

**Comment by deeyas** [comment]
@pramodvallanur I agree with your original comment: step-7 may not be needed. But I do not want to change that now because in the next steps I walk through **adding** and setting client ID + secret. (I'll have to update 1b, 2a for toolkit and for bluemix).
