### ISSUE TITLE
Step 17: Response

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#48]
Issue is for: https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/exposing-a-soap-service-as-rest

Could you add text to say, now for the response to the API call... basically provide some background to this step

In the Schema column of the 200 OK response in the Responses section, select your Weather Data Output definition

**Comment by kylien65** [comment]
Fixed.  Added "For the response to the API call, the object define in by the **Weather Data Output** will be the response object." verbiage to the step.
