### ISSUE TITLE
Reuse Service Import steps

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#49]
Issue is for: https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/exposing-a-soap-service-as-rest

Under Importing Services section, step 4 has a typo for wsdl.

Also could you add the screen shot from your previous tutorial around the file upload and default operation selection here as well

**Comment by kylien65** [comment]
Fixed

**Comment by kylien65** [comment]
Added image for step.
