### ISSUE TITLE
Gif for Deletion of Invoke

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#50]
Issue is for: https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/exposing-a-soap-service-as-rest

Could you add a gif for this as it is little tricky for first time users.

Delete the existing invoke policy on the canvas by hovering your cursor over the policy and then clicking the Delete policy icon

**Comment by kylien65** [comment]
Fixed.
