### ISSUE TITLE
Client ID removal

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#51]
Issue is for: https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/exposing-a-soap-service-as-rest

Do you want the user to remove client id from this tutorial as well. The previous tutorial of yours had this step

**Comment by kylien65** [comment]
No, it works either way.

**Comment by pramodvallanur** [comment]
Yes it would work for the tutorial. The above comment is that, for all other tutorials in this pack, we are asking the user to remove the client id. So want to make sure we are consistent. I am ok either way

**Comment by kylien65** [comment]
Fixed
