### ISSUE TITLE
Verify Path

### ISSUE THREAD

**Issue by jjtang1** [ibm-apiconnect/getting-started#53]
Was not very clear where/how to verify in my path in both sections. 
Suggest adding in "launching terminal" steps and code you can copy and paste in. 

<img width="956" alt="screen shot 2017-06-23 at 6 17 03 pm" src="https://user-images.githubusercontent.com/29666998/27502177-4b403f9a-5840-11e7-8abe-7585c127b151.png">

<img width="354" alt="screen shot 2017-06-23 at 6 17 08 pm" src="https://user-images.githubusercontent.com/29666998/27502176-4b221722-5840-11e7-88c7-1e2fc6f35554.png">

**Comment by jjtang1** [comment]
Also, in my screenshot vs. your screenshot, it looks different for step 4. Again, I was not sure how you got there. For a beginner, when they aren't identical it can cause confusion and skepticism.

![screen shot 2017-06-23 at 6 27 45 pm](https://user-images.githubusercontent.com/29666998/27502476-503fb9c4-5842-11e7-9b1a-74416dd35c88.png)
<img width="592" alt="screen shot 2017-06-23 at 6 28 05 pm" src="https://user-images.githubusercontent.com/29666998/27502477-5040ac1c-5842-11e7-8e03-2e69c8178aef.png">

**Comment by deeyas** [comment]
I added the command ```echo $PATH``` to supplement the instructions in the node installer wizard. Will not add step to launch terminal as this should be understood by the developer; we'll also have to ensure correct steps for mac/lin/win.

"Clarity around what to type in exactly would be helpful. "
I agree. Done.
