### ISSUE TITLE
Installing Node.js and API Connect

### ISSUE THREAD

**Issue by R11P11** [ibm-apiconnect/getting-started#54]
https://github.com/ibm-apiconnect/getting-started/blob/master/toolkit/0-Prereq/README.md#install-nodejs

We should specify which version of node. I installed 8.1.2 and it created errors later (at the Install the API Connect toolkit from npm
npm install -g apiconnect point) 
https://github.com/ibm-apiconnect/getting-started/blob/master/toolkit/0-Prereq/README.md#install-the-api-connect-toolkit

Tutorial says to check several things (e.g "Check the installed version and path "), and assumes the answer is yes, I encountered the answer being no and had to ask a developer to assist, at a minimum we could point to a community support forum in case the answer is no.

**Comment by Zach-Guilfoyle** [comment]
I'll alter the instructions to direct users to download the LTS version of node (6.11).  Need to keep an eye on updated LTS versions though.

What is the importance of checking the right path?

**Comment by ashumz** [comment]
I also have heard reports that the toolkit does not install properly with current version of node (8.1.2) - can we add that to the tutorial to make sure people know they will encounter errors and/or check if there is a workaround we can provide instructions for, to get the toolkit installed for those using the latest version of node?

**Comment by Zach-Guilfoyle** [comment]
Seems a little clumsy for the user.  Why is the latest version of Node giving APIC trouble?  I'd prefer to fix whatever is causing the incompatibility, if possible.

**Comment by R11P11** [comment]
Not sure what the importance of checking right path was. Maybe it confirms the install was correct and points in the right direction? Mine wasn't and I needed an assist to get it sorted out. Its possible that the target user for TK wont need to be hand-held like I was, but then again, a link to a community support forum if their path isn't as depicted means we don't just say "check that the path is ______ ." and remain silent on what to do if it is not.
