### ISSUE TITLE
Getting Started Creating an API in Node.js

### ISSUE THREAD

**Issue by R11P11** [ibm-apiconnect/getting-started#55]
https://github.com/ibm-apiconnect/getting-started/blob/master/toolkit/getting-started-creating-an-api-in-nodejs/README.md#add-a-new-model-and-data-source

Step 3 "Click the Data Sources icon ." there does not appear to be a data source icon. 
<img width="1604" alt="screen shot 2017-06-27 at 5 53 31 pm" src="https://user-images.githubusercontent.com/29641089/27612063-c5603b02-5b62-11e7-873e-93e930fcd00a.png">

CLI view
<img width="1434" alt="screen shot 2017-06-27 at 6 03 38 pm" src="https://user-images.githubusercontent.com/29641089/27612114-12312838-5b63-11e7-9968-93a468431d81.png">

**Comment by R11P11** [comment]
Re-tried, and now have data sources icon (and an API) this time selected default directory name "weather-data" rather than "weather-data directory" as above maybe https://github.com/ibm-apiconnect/getting-started/blob/master/toolkit/getting-started-creating-an-api-in-nodejs/README.md#create-a-loopback-project-from-the-command-line #3 "Enter the name of the directory in which to create the project. You can press Enter to use a directory with the same name as the project, or type a new name and press Enter. Needs to say not to change name, or maybe to repeat warning against including spaces in naming a directory?" 
<img width="1609" alt="screen shot 2017-06-27 at 10 16 42 pm" src="https://user-images.githubusercontent.com/29641089/27617844-d4bba4be-5b86-11e7-854f-d7e4d6c66059.png">

**Comment by R11P11** [comment]
https://github.com/ibm-apiconnect/getting-started/blob/master/toolkit/getting-started-creating-an-api-in-nodejs/README.md#test-your-loopback-project
"From the command line, enter the following command:

apic edit" 

Should I close the API Designer Explore tool after the last section of the tutorial -then re open it from the CLI using apic edit? Or is this just in case I jumped here out of order in the getting started tutorials?

**Comment by R11P11** [comment]
https://github.com/ibm-apiconnect/getting-started/blob/master/toolkit/getting-started-creating-an-api-in-nodejs/README.md#test-your-loopback-project "Start the local test servers by completing the following steps:" May need a comment about security dialog box possibility and "allowing" node to accept communications?

**Comment by R11P11** [comment]
https://github.com/ibm-apiconnect/getting-started/blob/master/toolkit/getting-started-creating-an-api-in-nodejs/README.md#test-your-loopback-project
What if I get an error 400 rather than 0 or 422? 
<img width="1301" alt="screen shot 2017-06-27 at 11 02 07 pm" src="https://user-images.githubusercontent.com/29641089/27618863-b239110a-5b8c-11e7-81b0-7a678a0e7b84.png">

**Comment by kylien65** [comment]
You don't need to exit Explorer and can continue from the preceding section.

Regards...Ky

**Comment by kylien65** [comment]
The 422 will result when you include the "ID" data element in the payload.  What payload are you sending to get the 400?  400 & 422 can be interpreted as the same.

Regards...Ky

**Comment by kylien65** [comment]
Please see my previous comment
