### ISSUE TITLE
Import your API spec, and proxy an existing REST service

### ISSUE THREAD

**Issue by R11P11** [ibm-apiconnect/getting-started#56]
https://github.com/ibm-apiconnect/getting-started/blob/master/bluemix/1a/README.md#import-the-sample-apps-openapi-spec-to-create-a-rest-api-proxy

My host was already set to "$(catalog.host)" and did not need to be renamed as mentioned in tutorial. 
<img width="1455" alt="screen shot 2017-06-27 at 11 22 03 pm" src="https://user-images.githubusercontent.com/29641089/27619389-eed4ad56-5b8f-11e7-9a46-a8cca21ade9b.png">

**Comment by R11P11** [comment]
https://github.com/ibm-apiconnect/getting-started/blob/master/bluemix/1a/README.md#test-your-api-proxy
"Choose the get /current operation." There appear to be two identical screenshots, it might be more valuable to show more than one of the steps, or just delete one of the duplicates.

**Comment by Zach-Guilfoyle** [comment]
Confirmed that $(catalog.host) is the default.  Tutorial edited and duplicate picture removed.
