### ISSUE TITLE
Getting Started Creating an API Node.js

### ISSUE THREAD

**Issue by jmjabour8** [ibm-apiconnect/getting-started#57]
**- Create Loopback Project From Command Line**
_Suggestion:_ Link to prerequesite of "Install Toolkit"
(+) These steps are already way better
(+) _i_ pieces of info are great and helpful

**- Add a Model**
9. Kinda tedious to add all 7 properties, could we do with just 3 or 4?

**- **Test Your Loopback Project****
1) When I type in "apic edit" into the already open command line, nothing happens
2) When I click the play button, it stays at "stopped" and doesn't go to "running"
_Solution:_ You don't need to do step 1 if everything is already open and you've already completed "Create Loopback Project" and "Test Loopback Project", just go straight to step 2

(+) Extra explanations are helpful -- not too much info but just enough to explain what's going on

6. Got an error here
(+) I got an error, but it told me why -- great!
_Suggestion_: If you get the error "failed to parse request body", you have to remove the comma following the last humidity_high number

**Comment by kylien65** [comment]
1. Added link to toolkit install.
2. The 7 properties are there to make the lab look some what consistent.
3. Add information to skip step 1 of test section if the user has not exited the APIC designer.
4. Added to troubleshooting section.
