### ISSUE TITLE
Import your API spec, and proxy an existing REST service -- BM

### ISSUE THREAD

**Issue by jmjabour8** [ibm-apiconnect/getting-started#58]
**Explore Sample App and Test Target Endpoints**
_Suggestion_:  Numbering the steps, rather than bullet points, makes things a lot easier to follow in my opinion
(-)  I don't think the app actually works yet -- it keeps coming up as "Armonk, NY", and the numbers for the temps seems randomly generated

**Import the sample app's OpenAPI spec to create a REST API proxy**
(-) In order to get to Drafts > APIs you have to click the tiny >> button -- this isn't clear and should be highlighted because it's not intuitive to click that button
(-) "You'll notice that the Host value is set to myweatherprovider.mybluemix.net..." -- This wasn't the case for me, it was already set to the correct $(catalog.host) value

**Test your API proxy**
(-) How do I save my API?
(+) Definition of APIs/Products/Catalogs relationship is really helpful

**Comment by deeyas** [comment]
updated steps
