### ISSUE TITLE
wsdl file issue

### ISSUE THREAD

**Issue by TWHolcombe** [ibm-apiconnect/getting-started#59]
@dkshute - I saw the previous closed issue regarding the location of the weather service wsdl file and found it based on link, saved to my system but I'm not able to import, bmx seems to get hung up, is there a good copy of the wsdl you can share?

**Comment by dkshute** [comment]
I just retrieved the file from git and used it in Bluemix and it parses fine.  You know you have to view the file as Raw and then save as, right.
 
Just in case, here is the file
 
 
 
 
David ShuteClient EnablementAPI Connectdshute@us.ibm.com978-899-2901 
 
 
----- Original message -----From: TWHolcombe <notifications@github.com>To: ibm-apiconnect/getting-started <getting-started@noreply.github.com>Cc: dkshute <dshute@us.ibm.com>, Mention <mention@noreply.github.com>Subject: [ibm-apiconnect/getting-started] wsdl file issue (#59)Date: Wed, Jun 28, 2017 10:12 AM 
@dkshute - I saw the previous closed issue regarding the location of the weather service wsdl file and found it based on link, saved to my system but I'm not able to import, bmx seems to get hung up, is there a good copy of the wsdl you can share?

**Comment by TWHolcombe** [comment]
Thanks, @dkshute was able to get it imported now
