### ISSUE TITLE
Add a new API spec and invoke an existing REST service -- BM

### ISSUE THREAD

**Issue by jmjabour8** [ibm-apiconnect/getting-started#60]
**Add a new OpenAPI spec and invoke an existing REST service**
3) "Drafts > APIs. Then click Add > New API" -- This is not intuitive in the interface, need to call out that you have to click the tiny >> button in order to get to "Drafts", then click on the API tab
8) How do I create a new path?  What button do I select?
(-) The word "Parameter" is not bolded and I couldn't find what to do because of it
(+) This is not your fault and this tutorial is great, but from a UI/UX stand point I think what you have to do steps 8-12 are not intuitive at all and was very frustrating -- gives Brielle and I another point to look into!
(-) When I save something I get distracted by the yellow sign with the exclamation point in it -- it makes me nervous because I feel like I'm missing something.  How do you get rid of this?

**Test Your API Proxy**
_Suggestion:_ At the end add a summary of what we did in this tutorial, like what was done in other tutorials

**Comment by R11P11** [comment]
3.) Agree with John's remarks, found it with some messing around. 
4.) If someone already completed another tutorial (Import OpenAPI2.0 spec & proxy existing REST service – BM) they may already have "Weather Provider API" and need to name it _2 or something. 

Test your API proxy: I'm sure its user error but I get an error 500, perhaps some mention of ways to check steps in tutorial vs only showing 200? 
<img width="351" alt="screen shot 2017-07-04 at 10 43 08 pm" src="https://user-images.githubusercontent.com/29641089/27847350-14c9730e-610b-11e7-9cee-ceac814bdc55.png">

**Comment by deeyas** [comment]
- updated steps 3,8,9 
- users need to start with 1a or 1b (but not both). I agree, this needs to be addressed, but I believe this needs to be handled  in the tutorial navigation. i.e. the user should know which tutorial to go to next. 
- I do not users should rename the api
- updated service url to prevent 500 that was root cause in this case
