### ISSUE TITLE
Import your API spec, and proxy an existing REST service -- TK

### ISSUE THREAD

**Issue by jmjabour8** [ibm-apiconnect/getting-started#63]
**Explore the sample app, and test the target endpoints**
(-) App weather info is randomly generated, just wanted to call this out again

**Test your API proxy**
(-) "Start the local test server by clicking on Start servers icon at the bottom of the screenshot_start-server-1" -- This is what it says right now, should probably change the last word to "screen."

_Suggestion_:  Add a summary of what we did in this tutorial

**Comment by Zach-Guilfoyle** [comment]
Edited steps and added summary at the bottom.  Need to follow up on sample app data output
