### ISSUE TITLE
Add a new API spec and invoke an existing REST service -- TK

### ISSUE THREAD

**Issue by jmjabour8** [ibm-apiconnect/getting-started#64]
Is there any difference between TK and BM versions?  The instructions look very similar if not the same.

**Add a new OpenAPI spec and invoke an existing REST service**
9) I get an "Invalid type: null (expected string)" error when I copy and paste the specified URL into the invoke policy, is this my fault or is there a problem with the URL?

_Suggestion_: Tutorial summary at the end would be great

**Comment by Zach-Guilfoyle** [comment]
Tutorial summary added.  Can you reload and see if the error is still present?  Also, is the test successful?
