### ISSUE TITLE
Exposing a SOAP service as REST

### ISSUE THREAD

**Issue by stillnotdanny** [ibm-apiconnect/getting-started#65]
In step 7, it says to 

> Leave the remaining fields unchanged.

and then the image and the UI does not match.
<img width="1076" alt="screen shot 2017-06-28 at 1 49 11 pm" src="https://user-images.githubusercontent.com/16959880/27652133-a168ee5a-5c08-11e7-8d4c-cd89227d275b.png">
<img width="827" alt="screen shot 2017-06-28 at 1 49 15 pm" src="https://user-images.githubusercontent.com/16959880/27652134-a1750b2c-5c08-11e7-9ed4-4b1f8407b7ad.png">

**Comment by kylien65** [comment]
Fixed
