### ISSUE TITLE
Setting up your API Connect instance - Spaces

### ISSUE THREAD

**Issue by butlerb12** [ibm-apiconnect/getting-started#72]
getting-started/bluemix/0-prereq/README.md

It would be nice to include a small description of a space similar to what was included to describe Products and Catalogs in "Testing the SOAP API Defn" included below:

In API Connect, Products provide a mechanism to group APIs that intended for a particular use. Products are published to a Catalog. [Reference: API Connect glossary]

**Comment by deeyas** [comment]
Did not call out "org" and "space" in the bluemix pre-reqs as those are bluemix-specific terms, and I did not want to introduce those from APIC POV. But did ensure the screenshots have details about the bluemix org and space.
