### ISSUE TITLE
Testing a SOAP API Definition - Outcome

### ISSUE THREAD

**Issue by butlerb12** [ibm-apiconnect/getting-started#74]
getting-started/bluemix/manage-soap-api/README.md

Haha, is the weather randomly generated? It was inaccurate, which I think would be a little off-putting for a potential client/developer trying out the service. I was a little disappointed after googling the weather in Armonk, NY. APIC says 57 degrees, google says 78 degrees.

**Comment by dkshute** [comment]
This issue is due to problems with the hosting of the back end service and nothing to do with this tutorial per se.
