### ISSUE TITLE
Update to Lite Plan

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#8]
The getting started pre-req for Bluemix to be updated to Lite Plan, instead of Essential

**Comment by deeyas** [comment]
Will update the instructions once Lite plans in available WW. And after connecting with @rgthelen.

**Comment by deeyas** [comment]
Updated https://github.com/ibm-apiconnect/getting-started/blob/master/bluemix/0-prereq/README.md
