### ISSUE TITLE
Test the changes made to your API - Step 1

### ISSUE THREAD

**Issue by butlerb12** [ibm-apiconnect/getting-started#80]
getting-started/bluemix/2a/README.md

Error thrown after "Republish product"

<img width="477" alt="screen shot 2017-06-29 at 12 13 41 pm" src="https://user-images.githubusercontent.com/9373875/27705946-8ace6cd0-5cc4-11e7-83c6-0c6d512d9db5.png">
<img width="445" alt="screen shot 2017-06-29 at 12 22 02 pm" src="https://user-images.githubusercontent.com/9373875/27706217-97aeb22e-5cc5-11e7-9422-a842e83c3465.png">

**Comment by deeyas** [comment]
@butlerb12 which tutorial did you complete before hitting this issue in bluemix-2a?
- 1a/importing  -- client ID is not in not saved in yaml, so should not hit this issue
- 1b/new spec -- need to delete client id (step 7 of "Add a new OpenAPI spec and invoke an existing REST service")

**Comment by deeyas** [comment]
unable to reproduce
