### ISSUE TITLE
Set the identification mechanism of your API

### ISSUE THREAD

**Issue by butlerb12** [ibm-apiconnect/getting-started#81]
getting-started/toolkit/2a/README.md

Running into issues here because I have tested toolkit so many times, can't seem to find this organization/space within my account. Weird that they are called projects in the toolkit but that term isnt used in bluemix?

<img width="833" alt="screen shot 2017-06-29 at 12 37 46 pm" src="https://user-images.githubusercontent.com/9373875/27706951-7000045a-5cc8-11e7-84f3-c23086c63b98.png">

**Comment by Zach-Guilfoyle** [comment]
Removed the "Re-publish" step, as it is unnecessary in the toolkit.
