### ISSUE TITLE
Basic Analytics

### ISSUE THREAD

**Issue by jmjabour8** [ibm-apiconnect/getting-started#82]
This might be the best tutorial in terms of layout, structure, and providing the right amount of background while still being short and concise.

**Activity 1: Viewing Out of the Box Analytics**
(+) Great job

**Activity 2: Viewing Event Details**
(+) Great job

**Activity 3: Building new dashboards**
2) When you click the 5 visualizations, you can't see that you're adding the visualizations because the tab that is opened blocks the original page.  Maybe just a warning of that here, because I was clicking and had no idea what was happening.

**Activity 4: Creating new visualizations**
(+) Great job

**Conclusion: Gaining insights**
(-) I think you forgot to take out "todo: insert screencap of graph here, after I build something attractive & simple"
(+) Great summary

**Comment by sunitajennings** [comment]
note added - good suggestion.
