### ISSUE TITLE
Analytics Activity 3: Building new dashboard - step 2

### ISSUE THREAD

**Issue by butlerb12** [ibm-apiconnect/getting-started#83]
getting-started/bluemix/analytics-basics/README.md

Not really a getting started issue, more of a UI flaw-- does not indicate when a new visualization is added to the new dashboard so I ended up clicking "subscribed apps" like 10 times and adding 10 of them to the dashboard (you shouldnt be able to do this more than once.) Just wanted to mark it for later because I think its an important design flaw.

**Comment by lana-li** [comment]
@sunitajennings may help to add a note in the tutorial on this to avoid confusion?

**Comment by sunitajennings** [comment]
@lana-li Note added. Also identified by @jmjabour8 in issue 82. I'll leave this issue open to track the design flaw (I wonder if you can move the issue elsewhere?) and close #82.
