### ISSUE TITLE
Manage SOAP API

### ISSUE THREAD

**Issue by jjtang1** [ibm-apiconnect/getting-started#87]
<img width="797" alt="screen shot 2017-07-05 at 4 08 12 pm" src="https://user-images.githubusercontent.com/29666998/27882805-2c2a4dfc-619c-11e7-94fc-dca31b77299d.png">

- there was no direct save option, instead, I just clicked raw and saved as txt file, was there a better way I missed?

**Comment by dkshute** [comment]
I haven't found any.

**Comment by jjtang1** [comment]
Is it worth specifying _click raw --> save as txt file_ ?

**Comment by dkshute** [comment]
Added this instruction.
