### ISSUE TITLE
Missing tutorial on LoopBack for /toolkit on creating apis from existing data sources and discovering models

### ISSUE THREAD

**Issue by ashumz** [ibm-apiconnect/getting-started#89]
Currently we have a tutorial on creating an API with Node using LoopBack and API Designer. This tutorial uses in the in-memory datastore and walks through creating your models in APID. This is good, but we should also be showing how you can create APIs from existing data sources (eg: mysql, DB2, etc) using loopback connectors, and then show how you can then discover models directly from the APID interface from your existing db schemas. 

For an example, this tutorial from the PoT is a good example of this functionality: https://ibm-apiconnect.github.io/pot/lab1_create_app.html

**Comment by lana-li** [comment]
noting this as discussion point for next phase
