### ISSUE TITLE
In the Bluemix navigation panel (left hand), select Services and click Dashboard

### ISSUE THREAD

**Issue by pramodvallanur** [ibm-apiconnect/getting-started#9]
Issue is for : https://github.com/ibm-apiconnect/getting-started/tree/master/bluemix/1a
Could we include a step in the pre-req on how to launch APIC service if they are coming back. Usually i am kind of lost, although its for the platform, a step would help

**Comment by deeyas** [comment]
Added screenshots under "Import the sample app's OpenAPI spec to create a REST API proxy"

https://github.com/ibm-apiconnect/getting-started/blob/master/bluemix/1a/README.md#import-the-sample-apps-openapi-spec-to-create-a-rest-api-proxy
