### ISSUE TITLE
Getting started discovering APIs - Alternative to DevPortal install

### ISSUE THREAD

**Issue by jjtang1** [ibm-apiconnect/getting-started#97]
Instead of going through the process of installing the developer portal locally I went into:

APIC on Bluemix --> Dashboard --> Sandbox --> Settings --> Portal --> Select Portal (IBM Dev Portal)

This was a quick work around to try out the tutorial.

**Comment by dkshute** [comment]
The Portal absolutely must be on Bluemix, otherwise the student must do a full on-prem install to do this unit.

**Comment by lana-li** [comment]
prereq fixed
