### ISSUE TITLE
Set Up Rate Limiting tutorial review (Bluemix)

### ISSUE THREAD

**Issue by jendavidse** [ibm-apiconnect/getting-started#99]
The following are my comments from my review of the set up rate limiting tutorial: 
https://github.com/ibm-apiconnect/getting-started/blob/master/bluemix/setup-rate-limiting/README.md

This is a good tutorial, well thought through and structured. My main comments are that all the tutorials should be consistent in their language and structure - I don't think they are currently. Also, the screenshots seem unnecessarily large - take up a lot of screen space. The rest of my comments relate to specific areas of the tutorial and are for the author to consider - I have made a lot of minor updates directly to the document in git already.

@lana-li @sjennings-ibm FYI
**Objective section**
The first mention of our product should be in full, ie IBM API Connect. After that we can use the short name.

It would be helpful to include more conceptual information here about what rate limiting means. For example, the first sentence could read
"This tutorial will show you how to set rate limits for your APIs. Setting rate limits enables you to manage the network traffic for your 
APIs and for specific operations within your APIs." There is a lot of good conceptual information in the KC that you could use to boost
this section: http://rtpdoc01.rtp.raleigh.ibm.com:9080/kc/SSMNED_5.0.0_test/com.ibm.apic.toolkit.doc/tapim_create_product.html
(See step 13.)

I think the description of Products/Plans could use a bit more information. For example, you explain that Products are used to group APIs together, 
and then say that Plans are used to differentiate between API product offerings... I found this a bit confusing. You could say that Products provide
a way of grouping APIs into a package for a particular use case. Products also contain Plans, and these Plans can be used to 
differentiate between different offerings. For example, you could have a "Demo Plan" that makes a single API available, and a "Full Plan"
that makes several APIs available. Plans also enable you to define rules associated with how application developers can access your APIs, 
such as whether subscription approval is required, and what rate limits are enforced. For example, a "Demo Plan" might allow a rate limit of 
ten calls per minute, while a "Full Plan" might allow up to 1000 calls per second.

I appreciate that you probably need to keep the overview brief, however, as this is aimed at newbies I think some background info into the 
concepts, especially the APIC terminology, would really help the user. Obviously, you can provide examples that match to the Weather API you use 
in the tutorial.

Remember that "Product" & "Plan" always have initial capitals (they are specific terms in APIC).

Think should change "1. Add a new rate-limiting plan to an existing API product.", to "1. Create a new rate-limited Plan in an existing Product."
This matches to your heading in the tutorial itself, and I'm not sure "API product" is a correct term (it could be an API Connect Product?).

**Prerequisites section**
Avoid positional statements like "below" as they fail accessibility checks, so maybe change "In the instructions below" to "In the following
instructions".

**Launch API Connect section**
Think we should be consistent across all the tutorials as to how to launch the product. Maybe match the Import your API spec and proxy an existing REST service
tutorial (https://github.com/ibm-apiconnect/getting-started/blob/master/bluemix/1a/README.md).

Step 4 should be moved to the next section (Explore the Default Plan), as it's not part of launching API Connect.

**Explore the Default Plan section** 
Need to describe how to get to the Products page more explicitly, as users could have clicked around on the site. For example, make Step 1 
"In the API Connect navigation panel, select *Drafts*. (If the navigation panel is not open, click >> to open it.)"
Then Step 2 can be "Select the *Products* tab, and you should see the Weather Provider API product listed."
For your reference, you should use "select" when someone needs to make a choice from a set of alternatives, and "click" for straightforward clicking of 
buttons & icons.

Step 3 becomes "Click the Product link, and the Design view opens listing information about the Product."

The rest of the step numbers should be changed accordingly.

**Create a new rate-limited plan section** 
Change "plan" to "Plan" throughout section.

Something's gone wrong with the Step numbering here - they are all bunched together? The Steps need to be separated out again. Think I've fixed it, but better check!

Step 5, be bit more specific about what the user has to click, eg "Click + to add a new rate limit." or "Click the *Add new rate* limit icon."

Step 6 (and previous step), "rate-limit" should not be hyphenated in standard text (obviously, keep the hyphens in the swagger names). Also, the user-input 
highlighting is over the wrong text - needs to be moved from "and set it to" to over the "1/1 Minute". Although actually this is the default setting, so you 
could just say "and ensure it is set to 1 call per 1 Minute."

**Stage & publish an updated product to the Sandbox catalog section** 
Change "product" to "Product" and "catalog" to "Catalog" throughout.

Step 1, if we can't put a picture of the icon to click, then we should give the icon a name, so in this case it should be "Click the Publish icon". Also, not sure why 
"Draft" has an initial capital? I've made it lower case, but please change back if there's a reason why this is a special term here.

Step 3, when choosing from a navigation menu, it should be "select", so change to "Select Dashboard,".

Step 5, think it would be useful to add a results section here, explaining that once the Product is published and made visible on the Developer Portal,
application developers can subscribe to the available Plans.

**Register a new (consumer) application section**
Think it would be useful to expand the title of this section to "Register a new (consumer) application in the Developer Portal" to make it clear we are moving
to different tooling.

Think this section needs some intro to the Dev Portal, explaining that application developers discover and use APIs by using the Developer Portal. If a Developer 
Portal hasn't been provisioned yet, they will need to provision a Portal first by creating an admin account. Then they will need to access the Portal and create an app 
developer account, and create an App, so they can explore and test the available APIs.

Step 1, substep 2, think needs more info about the email when provisioning the portal. Eg "When your Sandbox Developer Portal is ready, you will receive an email 
with a link to your Developer Portal site. The link is a single use only link for the administrator account."

**Conclusion section**
Would be good to give them some "what to do next" advice, eg recommend another tutorial.

**Comment by sunitajennings** [comment]
Made all changes, except for these 3 items:

Item: I'm not sure "API product" is a correct term (it could be an API Connect Product?).
Respone: this is the term used in the Developer Portal

Item: match the Import your API spec and proxy an existing REST service
tutorial (https://github.com/ibm-apiconnect/getting-started/blob/master/bluemix/1a/README.md)."
Response: I matched the wording, but not the URL. 

Item: Add "What to do next" / next tutorial info to Conclusion
Response: to be added by @lana-li when next tutorial is ready.
